### ISSUE TITLE
将Github Issues中的文章和个人博客相互同步

### ISSUE THREAD

**Issue by hankliu62** [hankliu62/toolbox-frontend#3]
## 未完成
- [ ] Github Issues到个人博客的同步

## 已完成 
- [x] 个人博客到Github Issues的同步

## 补充

github action 将用户创建的Issue自动生成Markdown 提交到指定项目

要实现这个功能，你可以使用 GitHub Action 和 GitHub API 来自动化这个过程。以下是一个实现的大致步骤：

1. 创建一个 GitHub Action，用于监听用户创建的 Issue 事件。
2. 当有新的 Issue 被创建时，GitHub Action 触发，并使用 GitHub API 获取 Issue 的相关信息。
3. 将获取到的 Issue 信息自动生成 Markdown，并提交到指定的项目。

以下是一个简单的示例 GitHub Action 的配置文件 `issue_auto_generate_md.yml`：
``` yaml
name: Issue Auto Generate Markdown
on:
  issues:
    types: [opened]

jobs:
  generate_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Generate Markdown
        id: generate_md
        run: |
          # 使用 GitHub API 获取新创建的 Issue 信息
          issue_title=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
          issue_body=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")
          # 生成 Markdown 内容
          echo "# $issue_title" > issue.md
          echo "$issue_body" >> issue.md
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generated markdown for issue"
          file_pattern: "issue.md"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
```

这个示例中，我们监听了 `issues` 事件，当有新的 Issue 被创建时触发。然后，我们使用 GitHub API 获取了新创建的 Issue 的标题和内容，并生成了对应的 Markdown 文件。最后，使用了 `stefanzweifel/git-auto-commit-action` Action 将生成的 Markdown 文件自动提交到指定的项目中。

在实际应用中，你可能需要根据具体需求进行调整和扩展。例如，你可以添加错误处理、自定义提交信息等。另外，需要注意的是，GitHub Action 默认情况下是没有权限直接访问其他仓库的，如果需要访问其他仓库，需要提供相应的权限。
